### ISSUE TITLE
always resolve with instance of HttpResponseMessage

### ISSUE THREAD

**Issue by jdanyow** [aurelia/http-client#10]
I'm doing some testing with the http-client as I work on the breeze ajax adapter. In situations where the xhr.onerror event occurs the http client is rejecting the promise with instance of the Error class. What do you think about letting it resolve with an instance of HttpResponseMessage? Same thing goes for the ontimeout event.

here's an example- in this case I'm debugging a dropped request. In the watch window you can see the HttpResponseMessage I newed up to see if it would work:
![debugger](http://i.imgur.com/nVCbkOU.png)

My reasoning here is send resolves in the case of 400/500/etc, might as well resolve in statusCode=0 type situations.

**Comment by EisenbergEffect** [comment]
I've fixed this up as of 43f3cf4ffdd9690bebb99cffe699eacf3477de94

**Comment by jdanyow** [comment]
Nice- thanks
