### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by heruan** [aurelia/http-client#104]
It would be awesome to have a binding to the upload progress of large files, e.g. to update a progress-bar widget. Does HttpClient already provide such a binding?

**Comment by bryanrsmith** [comment]
Yes, there's a `withProgressCallback` helper. Something like

```js
httpClient.createRequest('/blah')
    .asPost()
    .withContent(...)
    .withProgressCallback(updateProgress)
    .send();
```

**Comment by heruan** [comment]
Thank you @bryanrsmith! This unfortunately can't be used per-request with a configured HttpClient shortcut methods (e.g. `get()`, `put()`, …) methods unless configuring every request with all interceptors, revivers, etc.
I understand ES 6 promises lack support for a progress-callback (such a pity), so it would be nice to add a progress-callback as the last argument of all HttpClient shortcut methods.
Do you think it would be worth a PR?

**Comment by bryanrsmith** [comment]
Ah... that's pretty lame. I think it'd be better for `HttpClient.send()` to merge transformers instead of doing `transformers = transformers || this.requestTransformers` like it is now. That way per-request configurations would still share the client's configuration, but could override anything it needed. What do you think?

**Comment by heruan** [comment]
Interesting! How would you set a progress callback with HttpClient shortcut methods?
I was used to Q's `.then(success, failure, progress)` callbacks, but since ES6 doesn't support the progress concept I'm thinking about something like:
```typescript
post(url: string, content: any, progressCallback?: (event?: Event) => void): Promise<HttpResponseMessage> {
    builder: RequestBuilder = this.createRequest(url).asPost().withContent(content);
    if (progressCallback) {
      builder.withProgressCallback(progressCallback);
    }
    return builder.send();
  }
```
to be called with:
```javascript
http.post("/my/collection", item, progressCallback).then(successCallback, failureCallback);
```
and similar for other methods.

**Comment by bryanrsmith** [comment]
You wouldn't. The shortcut methods don't allow arbitrary configuration at
the moment. You'd need to use the full API to attach a progress callback.

**Comment by heruan** [comment]
I guess a progress callback would be a very useful tool (think about file uploads and such) and it should be easily attached to requests. Do you think the signature in my previous comment would worth a PR?

**Comment by bryanrsmith** [comment]
I don't know. I think the shortcut methods are nice because they're so simple and only support the basic use cases. If we start adding optional stuff they're not really any simpler or clearer than using the full API. I'd rather leave them as they are.
