### ISSUE TITLE
File upload support

### ISSUE THREAD

**Issue by giovannicandido** [aurelia/http-client#107]
Hi, 
The code:

```
let uploadFile = $("#upload");
        let file = document.getElementById("uploadFile").files[0];
        let formData = new FormData()
        formData.append("file", file);

        this.http.createRequest("rest/importar/upload").asPost().withContent(formData).send()
```
Send the file with a *content-type*  of *application/json* when the right content type is dynamic added by the XMLHttpRequest with some random file delimiter, like the one: 
```
    Content-Type: multipart/form-data; boundary=-----------------------------19101785007078931451097574330
```

**Comment by EisenbergEffect** [comment]
Call `skipContentProcessing()` on the request before sending and I think that will solve the issue.

**Comment by giovannicandido** [comment]
skipContentProcessing as no effect
Code used

```
let file = document.getElementById("uploadFile").files[0];
        let formData = new FormData()
        formData.append("file", file);
this.http.createRequest("rest/importar/upload").asPost().withContent(formData).skipContentProcessing().send()
```
Request still has **Content-Type: application/json**

Using HttpClient version *0.11.0*

To workround I'm using jquery to send the file, but jquery is not aware of my global request settings, like Cross Site Request Forgery protection, interceptions, and dev/production fits, so is not ideal because of code duplication.

**Comment by scardenas** [comment]
hasn't this issue been resolved yet?

**Comment by ne0guille** [comment]
im having the same issue with the fetch client

**Comment by paranoidandroid522** [comment]
Bump. Having the exact same problem with aurelia-http-client 1.1.1. Why was this issue closed?
