### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by denimaaark** [aurelia/http-client#108]
Hello,

typescript definitions are not updated or correct, for example

            this.http.post('/api/xxx'j)
                .then(response => {                
                    if (response.isSuccess){
                        this.navigateTo();
                    }
                })

.isSuccess is not in definition and vs show error.

So this is i think problem, because intellisense is not usable here, if i need to go to debugger and see there are more properties and methods ..

There are more not defined properties, not only .isSuccess, response only shows response.content

**Comment by EisenbergEffect** [comment]
Are you basing this off the current release, or off what is in master?...because I just did a ton of work in this area and committed it the other day. It's just not released yet.

**Comment by denimaaark** [comment]
I have install today clean default installation with jspm install aurelia-http-client

**Comment by EisenbergEffect** [comment]
Ok, yes. Those apis are missing from the d.ts in the current release. They will be in the d.ts for the next release, coming in the next week or two (the beta actually).
