### ISSUE TITLE
Easier header management

### ISSUE THREAD

**Issue by ShaneCourtrille** [aurelia/http-client#11]
It would be nicer if we could supply an array of headers to outgoing calls or something similarly easy.  If there is already a preferred way for us to manage headers that would be a good thing to add to the docs.

**Comment by zewa666** [comment]
Have you looked through the [unit-tests](https://github.com/aurelia/http-client/blob/master/test/http-client.spec.js) ... I'm not quite sure if the mentioned Header is something you are looking for but at least it sounds like so :)

As for documentation, like with all pre-beta stuff documentation is always sparse, so I'd always advice to take an additional look at the generated unit tests, cause those often helped me to understand what to do.

**Comment by ShaneCourtrille** [comment]
The problem with the unit-tests is they all new up an HttpClient.  I'd like to stick with DI.  And yeah defaultRequestHeaders is good for my current need BUT I still think an easy way to define headers for a single call (that allows me to keep DI and the HttpClient without any cleanup) is an important use case.  Sounds like something is planned though.

**Comment by jhoguet** [comment]
+1

example use case is sending a custom media type (`content-type`) on a post (eg `application/vnd.contact+json`) or even get requests. 

to get around this I had to create a new client instead of using the one from ioc

```js
import {HttpClient, Headers} from 'aurelia-http-client';
...
var headers = new Headers();
headers.add('content-type', 'application/vnd.contact+json');
var client = new HttpClient(undefined, headers);
```

I propose the following 

```js
http.post(url, content, [replacer], [headers])
```
where headers is of type headers so it doesn't conflict with replacer... final result might look something like

```js
http.post(url, content, new Headers({ "content-type" : "application/vnd.contact+json"}))
```

**Comment by GuillaumeJasmin** [comment]
You could simply do this:
```js
import {HttpClient} from 'aurelia-http-client';

export class MyClass{
    static inject() { return [HttpClient]; }
    constructor(http){
        http.defaultRequestHeaders.add('Content-Type', 'application/json; charset=utf-8');
    }
}
```

**Comment by ShaneCourtrille** [comment]
That is not simple compared to other frameworks AND you need to cleanup the
defaultRequestHeaders because httpclient is a singleton no?

**Comment by EisenbergEffect** [comment]
Major upgrade to http client in master, including a fluent api for requests. This will be releasing in the next couple of days.

**Comment by ShaneCourtrille** [comment]
The current tests in master don't show any improvement for this change unless HttpClient is no longer injected and we should always be creating an instance?

**Comment by EisenbergEffect** [comment]
You can configure HttpClient to be transient if you want, and always get a new instance. That's always been possible. However, the new api supports an additional way to make requests with a fluent API that enables customizing each request individually. So, you can do this:

```javascript
client.request
  .withHeader('foo', 'bar')
  .withCredentials(true)
  .get(uri);
```

Each chained method returns a request builder, until you call the verb, which returns the promise for the request. The previous API now runs on top of this, so we've confirmed that are original test suite passes with the new design. Some of the tests are using the new API as well. We need to add quite a few more tests to exercise it more fully.

**Comment by ShaneCourtrille** [comment]
Awesome.. cool :)

**Comment by matjaz** [comment]
docs should be updated. I was figuring out why I can't add `defaultRequestHeaders` :)

**Comment by MikeJoyce19** [comment]
It'd be nice if there was either a withHeaders call that accepts an array of kvp of header name and value or if withHeader had an overload accepting as much.

**Comment by slundberg** [comment]
Just a note for others, the syntax is no longer `client.request` but rather `client.createRequest()`:

```javascript
client.createRequest()
  .withHeader('foo', 'bar')
  .get(uri);
```
