### ISSUE TITLE
XHR object not passed to the RequestTransformer

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/http-client#113]
I'm not sure whether I'm using the `HttpCllient` correctly or not.
```
import {HttpClient, HttpRequestMessage, Headers, responseTypeTransformer} form 'aurelia-http-client';
var client = new HttpClient();
var req = new HttpRequestMessage('POST', someURL, data, Headers(headers));
client.send(req, [responseTypeTransformer]).catch(reason => {});
```
When this gets executed I get `Cannot set property 'responseType' of undefined` in the `catch`. It seems the problem is from here [`transformers[i](this, processor, message);`](https://github.com/aurelia/http-client/blob/master/src/http-client.js#L95), the xhr object is not passed to the transformer.

**Comment by EisenbergEffect** [comment]
Request transformers do not receive the xhr.
