### ISSUE TITLE
Pre-existing parameters in RequestMessage.buildFullUrl fails to properly include the parameter object

### ISSUE THREAD

**Issue by rebrown547** [aurelia/http-client#117]
Breeze Query Fails when a parameter object is included. When there are existing parameters, the parameter prefix should be '&' not '?'.
 
In 1.0.0-Beta.1 the following code RequestMessage.prototype.buildFullUrl should be :
      if (this.params) {
        var qs = _aureliaPath.buildQueryString(this.params);
        url = qs ? url + (this.url.indexOf('?') < 0 ? '?' : '&') + qs : url;
      }

**Comment by gregoryagu** [comment]
If you are using Breeze, you don't need to use the http-client.  Have you tried the Aurelia-Breeze plugin?  I use it, and it works great.

**Comment by EisenbergEffect** [comment]
Is this still an issue? If so, seems like a great opportunity for a community PR to address it. Shouldn't be too hard...

**Comment by gregoryagu** [comment]
I addressed this issue and sent pull request.

**Comment by EisenbergEffect** [comment]
Excellent. I just saw it come through. It will go out no later than Tuesday.
