### ISSUE TITLE
Transforming post request to x-www-form-urlencoded format

### ISSUE THREAD

**Issue by dlo83** [aurelia/http-client#12]
Hi there,

Just wondering if you could provide a snippet or give some direction as to how best to transform an http.post request to a x-www-form-urlencoded format within an Aurelia application.

The API I'm consuming relies upon this format.

Cheers,
Dan

**Comment by jus101** [comment]
+1

**Comment by EisenbergEffect** [comment]
You would use `FormData` like this:

```javascript
function sendForm() {
  var formData = new FormData();
  formData.append('username', 'johndoe');
  formData.append('id', 123456);

  http.post(url, formData);
}
```

Aurelia's http module is built on to p of XHR2. You find more info here: http://www.html5rocks.com/en/tutorials/file/xhr2/

**Comment by jus101** [comment]
According to https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#dom-xmlhttprequest-send XHR2 sends FormData as Content-Type: multipart/form-data.

I'm also working with an API that only accepts x-www-form-urlencoded. I got around this by doing the following:
```
this.http = new HttpClient()
  .configure(x => {
    x.withHeader("Content-Type", "application/x-www-form-urlencoded");
  });
```
and then:
```
this.http.post(url, jQuery.param(data));
```
Not the most elegant solution, but it is working.

**Comment by PWKad** [comment]
For anyone looking at this in the future, if you are creating your form data from a form (such as when uploading content to POST back to the server) you do *not* need to set the header at all, it's against the spec from what I can tell.  Let the client create the content-type header for you which will include the boundary the server needs to parse the content.

**Comment by chrisdostert** [comment]
to ammend comments by @EisenbergEffect  @PWKad and @jus101 : 
if you need to send with content-type of application/x-www-form-urlencoded you **do** need to set the Content-Type header and can url encode your form parameters (without external dependencies) as follows:
```javascript
http.createRequest(url)
            .asPost()
            .withHeader('Content-Type', 'application/x-www-form-urlencoded')
            .withParams({
                username: 'johndoe',
                id: 123456
            })
            .send();
```
