### ISSUE TITLE
HTTPClient.delete(url) sends undefined in request body on IE11

### ISSUE THREAD

**Issue by reinholdk** [aurelia/http-client#127]
The delete method serializes the empty request content as _undefined_ into the request body. This can cause a server to reject the request, if the server does not ignore the payload. The behavior of the server is in accordance to the HTTP/1.1 spec. (RFC 7231) which says:

> A payload within a DELETE request message has no defined semantics; sending a payload body on a DELETE request might cause some existing implementations to reject the request.

**Comment by EisenbergEffect** [comment]
@reinholdk This seems like an excellent opportunity to send a PR to fix the issue. Any interest?

**Comment by reinholdk** [comment]
@EisenbergEffect sure, I can prepare a fix.

**Comment by reinholdk** [comment]
@EisenbergEffect have signed the CLA some days back, but still getting a 403 when trying to push may change. Any idea?

**Comment by EisenbergEffect** [comment]
You can't push a change to our repro. You need to submit a pull request. Then, we will review the change and merge.

**Comment by Alexander-Taran** [comment]
pull request merged
can be closed?
