### ISSUE TITLE
Multivalued header in Microsoft Edge

### ISSUE THREAD

**Issue by heruan** [aurelia/http-client#128]
I don't know if this is a `http-client` or browser issue, but when I receive a response with a multivalued header, in Microsoft Edge I get strange out-comings. For example, given this response:

```
HTTP/1.1 200 OK
Link: <http://example.org/foo>; rel="foo"
Link: <http://example.org/bar>; rel="bar"
Link: <http://example.org/bar>; rel="baz"
```

in `HttpResponseMessage.headers` in Chrome I have an object with a comma separated list of repsonse `Link` header values:

```
{
    "Link": "<http://example.org/foo>; rel=\"foo\",<http://example.org/foo>; rel=\"bar\",<http://example.org/foo>; rel=\"baz\""
}
```

but in Edge I have this:

```
{
    "": "<http://example.org/foo>; rel=\"bar\"",
    "Link": "<http://example.org/foo>; rel=\"baz\""
}
```

is it a bug in the `XHR` implementation of Edge, or a `http-client` one?

**Comment by EisenbergEffect** [comment]
@heruan I'm not immediately sure the answer to your question. Has your research turned up any additional insights?

**Comment by heruan** [comment]
@EisenbergEffect Yes, I found out that the string passed to [http-client/src/headers.js#L76](https://github.com/aurelia/http-client/blob/master/src/headers.js#L76) differs in IE/Edge when it contains multi-valued headings. For example, given this HTTP response message:
```
HTTP/1.1 200 OK
Content-Type: application/json
Link: <http://example.org/foo>; rel="foo"
Link: <http://example.org/bar>; rel="bar"

{}
```
in Chrome at [http-client/src/headers.js#L76](https://github.com/aurelia/http-client/blob/master/src/headers.js#L76) we have this `headerStr`:
```
Content-Type: application/json
Link: <http://example.org/foo>; rel="foo", <http://example.org/bar>; rel="bar"
```
and the `parse` function produces this `Headers` object:
```javascript
{
    'headers': {
        'Content-Type': 'application/json',
        'Link': '<http://example.org/foo>; rel="foo", <http://example.org/bar>; rel="bar"'
    }
}
```
while in IE/Edge at [http-client/src/headers.js#L76](https://github.com/aurelia/http-client/blob/master/src/headers.js#L76) we have this `headerStr`:
```
Content-Type: application/json
Link: <http://example.org/foo>; rel="foo"
Link: <http://example.org/bar>; rel="bar"

```
(Notice the last blank line!) and the `parse` function produces this `Headers` object:
```javascript
{
    'headers': {
        '': 'application/json',
        'Link': '<http://example.org/bar>; rel="bar"'
    }
}
```
where somehow the first key disappeared and the multivalued heading got collapsed in its last value.

Now, some considerations. First, I do not consider this a bug of `http-client` since the specs at https://www.w3.org/TR/XMLHttpRequest:
- at 4.7.3 explicitly say that multivalued headings should be concatenated by a comma;
- at 4.7.4 do not show a blank line in the example.
Unfortunately this IE/Edge strikes `http-client` users and I don't know if Aurelia should workaround this; how did you treat cases like this?

Second, this is correlated to https://github.com/aurelia/http-client/issues/77 since multivalued headings are a real thing and many HTTP APIs handle them. I'd like to PR an extended `Headers` object totally backwards-compatible where the `get(headerName)` works the same (returns the concatenated values) but also provides a `getAll(headerName)` which returns an array of values.

Obviously, this issue about the parsing should be handled first, would itself the parsing change.

**Comment by heruan** [comment]
Is this closed as fixed?

**Comment by EisenbergEffect** [comment]
This was marked as a question. The related feature request is still open.
