### ISSUE TITLE
.withParams() does not serialize dates

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/http-client#130]
https://gist.run/?id=50c90cd2a73b45026209c46a3b949bd1

```
import {inject} from 'aurelia-framework';
import {HttpClient} from 'aurelia-http-client';

@inject(HttpClient)
export class App {
  constructor(httpClient) {
    this.httpClient = httpClient;
  }
  
  attached() {
    let request = this.httpClient.createRequest('https://some.unexisting.domain.name.com')
    .asGet()
    .withParams({a: 'a', b: new Date()});
    
    request.send();
  }
}
```

The `b` parameter is lost, while the `a` parameter is sent:

![image](https://cloud.githubusercontent.com/assets/2189477/14227038/905a2a94-f8f3-11e5-8cb5-62300f3fec26.png)

**Comment by JeroenVinke** [comment]
Or should we just serialize the date before passing it to `.withParams()` ?

**Comment by EisenbergEffect** [comment]
Closing this since you should probably serialize the dates to format you desire before sending.
