### ISSUE TITLE
`POST`ing assumes multipart form data rather than `x-www-form-urlencoded`

### ISSUE THREAD

**Issue by no1melman** [aurelia/http-client#133]
I've executed this code:

```
this.http
    .createRequest('login')
    .asPost()
    .withContent(data)
    .withHeader('Content-Type', 'application/x-www-form-urlencoded')
    .send()
    .then(result => {
          console.log(result);
     });
```

And the request always does this:

```
------WebKitFormBoundaryyWpTQqCrgvgO3wxN
Content-Disposition: form-data; name:"passcode"

adsa
------WebKitFormBoundaryyWpTQqCrgvgO3wxN--
```

When I expect it just to create proper Form Data.

```
passcode:dsadas
```

**Comment by EisenbergEffect** [comment]
I've tested this and it seems to work correctly. The response header is being transmitted correctly and the form data is in the proper format. I've also reviewed the code and can't see anything that would alter the content type header if it was set as above. In an earlier version of the client, there was a bug related to content type which was fixed.

**Comment by no1melman** [comment]
If it is fixed then that's awesome.
