### ISSUE TITLE
jsonp clean up calls removeNode which fails on missing parent param

### ISSUE THREAD

**Issue by waxenegger** [aurelia/http-client#134]
https://github.com/aurelia/http-client/blob/master/src/jsonp-request-message.js#L46

Seems a bit strange... debugging it I see that the script element is appended to the body since no parent node was given. After that it has a parent node, yet at the point it time when cleanUp is called that parentNode is null...

if I change the script tag to be appended to the head it seems to work:
DOM.appendNode(script, DOM.querySelectorAll('head')[0]);

Could it be that this is happening because I'm requesting before  aurelia.start()?
But then again it has assigned to the body (I see in the debugger) so clearly it does exist in the dom model at that point in time or is it just the abstraction ???

**Comment by EisenbergEffect** [comment]
If you are doing this and then calling start, the call to start/setRoot will change the structure of the host element, which is the body by default. That results in the script already being removed and parent being null. I've added some logic to our browser platform abstract to guard against null/undefined parent nodes.
