### ISSUE TITLE
How to pass parameters over GET request

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/http-client#139]
There is documentation or sample that shows how to pass paramteres in get request.
i tried  that and it isn't working:
`this.http.get('api/someapi', {
                    cid:parseInt(cid,10),
                    sessionId: gameId
                });`

**Comment by EisenbergEffect** [comment]
You can create the request and use the `withParams()` method to add the params. The method is listed in the docs but there isn't a code example. Feel free to submit a PR to the doc to add it.
