### ISSUE TITLE
how to catch the jsonp ERR_CONNECTION exception which called in "activate" ?

### ISSUE THREAD

**Issue by liuyuanhuo** [aurelia/http-client#14]
Hi,
how to catch the jsonp ERR_CONNECTION exception which called in "activate" ?
(this issue move from 'skeleton-navigation' module's issue list)

![flick js](https://cloud.githubusercontent.com/assets/8426293/6061326/ab05a3c8-ad81-11e4-9724-8692cb645caa.png)

![blocked jsonp](https://cloud.githubusercontent.com/assets/8426293/6061235/ecb5b2c8-ad80-11e4-8715-4cd627ae5e3c.png)

**Comment by EisenbergEffect** [comment]
We've implemented a timeout capability that can be used for this. It's going out in the next http release tomorrow or the next day.
