### ISSUE TITLE
Problem with BLOB Binary Data,

### ISSUE THREAD

**Issue by horseyman** [aurelia/http-client#141]
Hello, 

I am using the aurelia-http-client library to get binary (Excel) data from a REST service, and store it to file
(using a Blob).
When I implement the service as a simple GET and perform it in any browser, the Excel data is well received. However, when I perform the GET using the aurelia-http-client, the data (the content property of the response) is NOT well received, and results in a FILE of larger size that cannot be well processed by Excel.

Acorrding to what I read in https://github.com/aurelia/http-client/issues/93, it should "just work".

I am using version "npm:aurelia-http-client@^1.0.0-beta.1.2.0".

Best regards, looking forward to a solution..

**Comment by EisenbergEffect** [comment]
If you are reporting a bug, we can't help you if you don't fill out the issue template.

**Comment by horseyman** [comment]
sorry

**Comment by MMJM** [comment]
@horseyman Hi. Did you ever get this working as I'm having the same issue I think.

**Comment by horseyman** [comment]
hello @MMJM,  i didn't get this working, so far I could avoid this problem using simple HTTP GET, forgot to fill out the Issue Template so far..

**Comment by MMJM** [comment]
@horseyman Nope me either. I have switched to the request package on NPM and got this working pretty easily. It also allows me to use the throttle package I needed as data comes down.

**Comment by MMJM** [comment]
@horseyman BTW I did submit an Issue

**Comment by horseyman** [comment]
@MMJM  So you stopped using aurelia in favor of Request? Don't you use any other Client functionality of Aurelia, or do you combine Aurelia with Request for just the HTTP traffic? I'll look up the throttle package, haven't heard of that one.

**Comment by MMJM** [comment]
@horseyman I just switch using Aurelia's HTTP-ClIENT to REQUEST. I had spend a day or so trying to get Aurelia's HTTP thing working with blobs but ended up getting Request running and saving a file within an hour. I still plan on using Aurelia for things other than http processing.
