### ISSUE TITLE
http post pass the parameters over the url

### ISSUE THREAD

**Issue by eliavmaman** [aurelia/http-client#144]
hey
I'm truing to create a post request to the server like that:
```
return this.http.createRequest('api/someApi').asPost().withParams({
            cid: parseInt(cid, 10)
        }).send();
```
the strange thing  i see is that
![image](https://cloud.githubusercontent.com/assets/6911449/17333720/19c863d4-58dc-11e6-9397-41f75cadae98.png) 
 the method is POST but the params passed over the url.
also the section of query string params is full
![image](https://cloud.githubusercontent.com/assets/6911449/17333769/503f2ad8-58dc-11e6-80b6-a5cb398bfe41.png)

the request ofcourse  doesn't get to the server.

**Comment by ignusk84** [comment]
14 days later and no feedback?

**Comment by EisenbergEffect** [comment]
It's an issue with the server, now Aurelia's library. Also, Github isn't the place for questions. This is better handled on gitter or SO.
