### ISSUE TITLE
responseType field is missing in HttpResponseMessage declaration

### ISSUE THREAD

**Issue by gamtiq** [aurelia/http-client#149]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Current behavior:**
`responseType` field is added to an instance in `HttpResponseMessage` constructor.
But the field is not declared in the class nor in `.d.ts` file.

**Expected/desired behavior:**
Add `responseType` field to class declaration and `.d.ts` file.

**Comment by EisenbergEffect** [comment]
@gamtiq We'd love to have you contribute to the project by submitting a PR to add this. All you have to do is add it directly in our JavaScript source. Do you have any interest in doing that?

**Comment by gamtiq** [comment]
@EisenbergEffect Ok, I'll add the field into [HttpResponseMessage](https://github.com/aurelia/http-client/blob/master/src/http-response-message.js) class. I'll make a PR in a day or two.

**Comment by niemyjski** [comment]
Perhaps this should be typed like it is with the fetch client
