### ISSUE TITLE
Headers are not treated as case insensitive

### ISSUE THREAD

**Issue by fragsalat** [aurelia/http-client#152]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 16.04

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
any

* **Browser:**
all | Chrome | Firefox

* **Language:**
all

**Current behavior:**
The current implementation of Headers isn't case-insensitive since the `get(key: string)` function just uses the argument as an key without any normalization. If the response header name was `ETag` and I try to get `etag` the function `has(key: string)` returns true because it's case insensitive, but `get(key: string)` returns false because it's case sensitive.

**Expected/desired behavior:**
Regarding the [RF2616 section 4.2](https://tools.ietf.org/html/rfc2616#section-4.2) standard all message header names (general-, request-, response- and entity-headers) has to be handled as case insensitive.

* **What is the expected behavior?**
With response header `ETag: soemthing` the function `get(key: string)` and `has(key: string)` should return true with the parameter `etag`, `ETAG`, `ETag` and any other case combination.

* **What is the motivation / use case for changing the behavior?**
Firefox 49.0 seem convert the Header names in some abstruse way while Chrome 51.0.2704.79 doesn't. Therefore headers in Chrome are handled properly but not in Firefox and the other way.

**Comment by EisenbergEffect** [comment]
@fragsalat Any interest in making a PR to fix this?

**Comment by fragsalat** [comment]
@EisenbergEffect I'll do for sure :smile:

**Comment by EisenbergEffect** [comment]
Fantastic. Thank you!

**Comment by heruan** [comment]
This is pretty urgent: starting with the latest Chrome version (53.0.2785.143) all header names are lowercased and it breaks content-type recognition, thus breaking any Aurelia application which trusts http-client's responseType.
