### ISSUE TITLE
Custom headers not accessible in CORS response

### ISSUE THREAD

**Issue by Beijerinc** [aurelia/http-client#154]
**I'm submitting a bug report**

* **Library Version:**
1.0.1 (aurelia-fetch-client)

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.3.1

* **NPM Version:**
3.19.6

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
Chrome 54

* **Language:**
TypeScript 1.8.10

**Problem**
Our application is in need of cookie support. We use a cookie for authentication but also for some additional contextual information that is required for every request. Since cookies are not stored and resent by the browser using aurelia-fetch-client, and manual manipulation of cookies is impossible in our CORS scenario, I decided to use custom headers instead. However, I am unable to access any custom header through the fetch client, regardless of what CORS headers I allow or expose. Here are my requests:

**Preflight**
> OPTIONS http://localhost/application/api/authentication/logon HTTP/1.1
> Host: localhost
> Connection: keep-alive
> Access-Control-Request-Method: POST
> Origin: http://localhost:9000
> User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
> Access-Control-Request-Headers: content-type, useheaderauthentication
> Accept: */*
> Referer: http://localhost:9000/
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4

> HTTP/1.1 200 OK
> Cache-Control: private
> Content-Length: 0
> Server: Microsoft-IIS/7.5
> Access-Control-Allow-Headers: X-PINGOTHER, Content-Type, UseHeaderAuthentication, **.ASPXFORMS**
> Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST
> Access-Control-Expose-Headers: **X-Powered-By**, **.ASPXFORMS**
> Access-Control-Allow-Origin: *
> Set-Cookie: ASP.NET_SessionId=nsmtikoeymxq35fobe41pdxu; path=/; HttpOnly
> X-Powered-By: ASP.NET
> Date: Tue, 18 Oct 2016 13:06:59 GMT

**Actual Request**
> POST http://localhost/application/api/authentication/logon HTTP/1.1
> Host: localhost
> Connection: keep-alive
> Content-Length: 73
> Origin: http://localhost:9000
> useheaderauthentication: true
> User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36
> content-type: application/json
> Accept: */*
> Referer: http://localhost:9000/
> Accept-Encoding: gzip, deflate, br
> Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
> 
> {"userName":"myUser","password":"myPass"}

> HTTP/1.1 200 OK
> Cache-Control: private
> Pragma: no-cache
> Content-Length: 4
> Content-Type: application/json; charset=utf-8
> Server: Microsoft-IIS/7.5
> Access-Control-Allow-Origin: *
> Set-Cookie: ASP.NET_SessionId=zcr00p2ss2jsya2hyozqfses; path=/; HttpOnly
> Set-Cookie: .ASPXFORMS=325BFCD~CA1; path=/; HttpOnly
> **.ASPXFORMS**: 325BFCD~CA1
> **X-Powered-By**: ASP.NET
> Date: Tue, 18 Oct 2016 13:06:59 GMT
> 
> true

**Code**
The point is that the .ASPXFORMS header is resent back to the server for every request, once it has been obtained. It is specified in ~Allowed-Headers to make that possible. The ~Expose-Headers doesn't seem to be adhered to, since I am unable to access the X-Powered-By and .ASPXFORMS headers with the following code:

```
var i: string[] = [];
response.headers.forEach((x, y) => i.push(y + "=" + x));
```

from either an interceptor or the 'then' after the fetch call:
```
http.configure(config => {
	config.
		useStandardConfiguration().
		withBaseUrl(baseUrl).
		withDefaults({
			headers: {
				"UseHeaderAuthentication": "true"
			}
		}).
		withInterceptor(authenticationInterceptor).
		withInterceptor(errorInterceptor);
});

@autoinject
class AuthenticationInterceptor {
	response(response: Response) {
		var i: string[] = [];
		response.headers.forEach((x, y) => i.push(y + "=" + x));

		return response;
	}
}
```

All I get are 3 headers: Cache-Control, Pragma and Content-Type. Am I doing something wrong or is the Access-Control-Expose-Headers header simply not implemented yet?

**Comment by EisenbergEffect** [comment]
@bryanrsmith Do you know anything about this?

**Comment by bryanrsmith** [comment]
I don't see anything obviously wrong. This library directly returns the response without reading it, though. There's nothing to implement on our end to add support for Access-Control-Expose-Headers. I know at one point Chrome had some off behavior when making cors requests to localhost, and I don't know if that's still the case. Do you get a different result in Firefox, or another browser using a fetch polyfill? If so, try using a hosts file hack to add an alias for localhost.

**Comment by Beijerinc** [comment]
Firefox does the same thing. It would be weird thing to be broken in the basic fetch client, because I'm seeing a bunch of answers on StackOverflow suggesting to add an Access-Control-Expose-Headers as a solution. Thanks for taking a look at this though, I'll post it on the fetch client's git and see if they have any suggestions. I'll close the issue, since it's not an aurelia problem.

**Comment by Beijerinc** [comment]
To report back, the problem turned out to be that the actual response didn't contain the Access-Control-Expose-Headers header. I thought it was a CORS 'configuration' type thing, but this header (like ~Allow-Origin) is slightly different in that it must be specified on (at least?) the actual response as opposed to only on the preflight. In short: it works now, thanks again.

**Comment by gmkhussain** [comment]
Set **access-control-expose-headers', '*'**

Example:
```js
router.get('/your-route', async (req, res) => {
    //..
    res.setHeader('access-control-expose-headers', '*' );
    //..
})
```
