### ISSUE TITLE
Passing ArrayBuffer as content produces unintuitive behavior

### ISSUE THREAD

**Issue by stickfigure** [aurelia/http-client#161]
**I'm submitting a bug report**

* **Library Version:**
1.0.4

**Current behavior:**
Passing an ArrayBuffer to `withContent()` causes the `contentTransformer` to convert the body to an empty JSON object (`{}`).

**Expected/desired behavior:**
I expected passing an ArrayBuffer to `withContent()` would send the binary data as a payload. If for some reason ArrayBuffer is not allowed, I expected some sort of error message. 

Silently converting it to JSON is super confusing and it took me a while to notice that the payload was not the binary I expected, then to figure out why :-(

The guilty code:
https://github.com/aurelia/http-client/blob/master/src/xhr-transformers.js#L90

**Comment by EisenbergEffect** [comment]
Definitely appears to be a bug. The ArrayBufferView should probably be changed to ArrayBuffer. Any interest in submitting a PR?

**Comment by maurice-camp** [comment]
Also experiencing this issue. Created a pull request to fix this for ArrayBuffers.

This does not fix the issue however when sending ArrayBufferViews such as 'Uint8Array'.
