### ISSUE TITLE
[Breaking] version 1.2 query changes breaks client.configure(o => o.withParams(params))

### ISSUE THREAD

**Issue by niemyjski** [aurelia/http-client#170]
We had our packages automatically upgraded from 1.1.1 to 1.2.0 via the minor `^` and this broke us pretty hard. Our entire app had no query strings applied.

Here is the code where we were passing `params` that was an object that contained the query strings..

```js
  private getClient(params: any = null, contentType: string = "application/json") {
    var client = new HttpClient();
    client.configure((o: RequestBuilder) => {
      o.withBaseUrl(this.baseUrl);
      o.withHeader("Content-Type", contentType);
      o.withParams(params);
      o.withInterceptor(new ExceptionlessHttpInterceptor($ExceptionlessClient));

      if (this.token != null) {
        o.withHeader("Authorization", "Bearer " + this.token);
      }
    });

    return client;
  }
```

**Comment by EisenbergEffect** [comment]
We didn't intend any breaking changes. I've reviewed the code and can't see how/why this wouldn't work. Can you provide some further details? or a PR to fix the bug?

**Comment by EisenbergEffect** [comment]
Ah. I think I see the issue. Let me make a fix and get a release out. Stand by. Apologies!

**Comment by EisenbergEffect** [comment]
Ok, we've pushed out a patch to fix the regression.

**Comment by niemyjski** [comment]
Awesome, thank you
