### ISSUE TITLE
statusCode 500, throw statusCode 0 

### ISSUE THREAD

**Issue by tbnovaes** [aurelia/http-client#180]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.3

* **Node Version:**
9.4.0

* **NPM Version:**
5.7.1

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
I'm using responseError interceptor, and when I was logging my errors, every 500 error, was being logged as 0.

<img width="1680" alt="screen shot 2018-03-15 at 1 28 05 pm" src="https://user-images.githubusercontent.com/5142733/37480283-33a0590c-2855-11e8-8c1e-e078fdc3e3aa.png">

**Expected/desired behavior:**
Expected to have the correct error thrown

* **What is the motivation / use case for changing the behavior?**
I'm trying to handle my 500 errors and currently it is not possible as they are treated as 0.

**Comment by Alexander-Taran** [comment]
can you try to pinpoint the issue to the code in http-client?

**Comment by tbnovaes** [comment]
@Alexander-Taran I'm closing this issue. I spent the entire day debugging today, and it turned out that the bug was on the API side. The cors headers where not being returned on 500 errors, so the interceptor was interpreting as network error and giving me status 0.
