### ISSUE TITLE
Cannot set header in 0.5.2

### ISSUE THREAD

**Issue by yale** [aurelia/http-client#19]
Hi! I'm not able to set a header on 0.5.2, neither by using the configure function nor the withHeader function:

```es6
import {HttpClient} from 'aurelia-http-client';

export class Spacemoney{
  static inject() { return [HttpClient]; }

  constructor(http) {
    this.env = 'development';
    this.apiToken = '...';
    this.http = http.request.withHeader('Authorization', 'Token token="' + this.apiToken + '"');
  }
  ...
}
```

When the request is made, no Authorization header is set. Let me know if there's any more information I can provide that would help.

BTW, I have been building a sideproject using Aurelia for the past 72 hours, and I am in love. I'm so excited to see this project mature!

**Comment by EisenbergEffect** [comment]
We have tests case that verify that this works. So, something unexpected is going on. Is it possible for you to create a test case for this that fails?

**Comment by yale** [comment]
Ah! jsonp does not permit setting HTTP headers, since it's executed using a script tag src. No bug to see here folks!

**Comment by EisenbergEffect** [comment]
Glad you worked it out.Thanks for updating us!

**Comment by janvanderhaegen** [comment]
Just for future reference, Authorization header is never sent unless you do CORS (see #43)
