### ISSUE TITLE
All POST requests being sent twice.

### ISSUE THREAD

**Issue by geefinator** [aurelia/http-client#25]
As far as I can tell in version 0.5.3, all of my POST requests are being sent twice.  Once with the proper data I would expect (though this seems to happen silently as it is not picked up by the dev tools in browser, but it is in my api server's logs.), then a second time with the payload of nothing for all data variables.  So basically, every time I post, I am seeing two separate POST requests to the api server.  One that is legitimate and one that is just a garbage request with no data payload.

![developer_tools_-_http___localhost_9000__](https://cloud.githubusercontent.com/assets/1870517/6654642/7fe45668-ca9f-11e4-8b2e-df3b4dcab8f6.png)

an example request with empty payload

![carriage_ _root_carriage-api___var_www_carriage_current_ _ssh_ _150x44_and_developer_tools_-_http___localhost_9000__](https://cloud.githubusercontent.com/assets/1870517/6654643/8c6d40ac-ca9f-11e4-9e54-eddd19a9273d.png)

Excerpt from the api server logs showing two posts back to back, one with the data, one without.

My code is fairly straight forward:

<pre>
  addOrganization(){

    var json = {
      'name': this.org_name,
    };
    return this.http.post(this.new_org_url, json).then(response => {
      var dataobj = JSON.parse(response['response']);
      if (response['statusCode'] == 201){
        console.log('Success');
      }else{
        alert("something went wrong");
      }
    });
</pre>

**Comment by geefinator** [comment]
Just to update, as you will notice I was allowing the bad requests to save as objects on the api.  I went ahead an threw a 400 if the data was empty, and sure enough as I expected, the http-client ignored the 400 and came back with the 201 (of the good request with the proper data).

**Comment by zewa666** [comment]
Hi there,

I've created a Unit Test to check whether it's an API issue. Seems not to be so. Here is the code if you wan't to check it yourself:

```
      it('should make only one request (Issue #25)', () => {
        var content = { name: "A demo name" };
        var client = new HttpClient()
          .configure(x => {
            x.withBaseUrl(baseUrl);
            x.withHeader('Content-Type', 'application/json');
          });

        client.post('some/cool/path', content);

        console.log(jasmine.Ajax.requests.count());

        expect(jasmine.Ajax.requests.count()).toBe(1);
      });
```

So I guess it's related to something specific to your application. Dunno maybe you're calling the method by incident a second time or so. Just add a breakpoint to your `addOrganization()` method to see if it's executed twice.

**Comment by geefinator** [comment]
The addOrganization() function is only being called upon a form submittal.  So unless the form is being submitted twice, I am not sure how my application would be making double requests.   Just the behavior of the two requests really seems like a bug somewhere.  One was completely silent as far as dev tools was concerned, the other was not.  I will take a look again at my code, but it really is dead simple whats going on.

**Comment by geefinator** [comment]
And now it seems to no longer be doing it at all.  *shrug*.  I did do some refactoring of all that code so i suppose I must of been doing something whacky previously.  Thanks for taking the time to write up a test case for my own error :)

**Comment by zewa666** [comment]
No problem at all. Glad it got solved
