### ISSUE TITLE
Cannot install with npm

### ISSUE THREAD

**Issue by troch** [aurelia/http-client#26]
I am trying to use aurelia-http-client commonjs dist through npm (not an aurelia.io app, bundled with browserify):

     $ npm install --save aurelia-http-client

but get the following error:

    npm ERR! 404 404 Not Found: aurelia-http-client
    npm ERR! 404
    npm ERR! 404 'aurelia-http-client' is not in the npm registry.

**Comment by zewa666** [comment]
This is because we provide our repos via JSPM. There is no NPM package registered for those repos

**Comment by troch** [comment]
OK, my mistake. I thought the line `"main": "dist/commonjs/index.js` in `package.json` was intended for release through npm.

**Comment by EisenbergEffect** [comment]
@troch Can you tell me a bit more about your use case? We could publish it to npm, but we haven't up to this point since people have been fine with jspm and bower. I'd like to know more so we can see if we need to provide some/all modules another way.

**Comment by troch** [comment]
One of my playground application uses React.js. I am trying to see if I can pick Aurelia's http client as my xhr library, play with its features, etc... The application is bundled using browserify, thus why I thought I could access the commonJS release through npm.

**Comment by EisenbergEffect** [comment]
Gotcha. I would try doing `npm install github.com/aurelia/http-client` or something like that. npm can actually install directly from the repo, so I think that should do it, since the package json is set up correctly for npm. Give it a shot, if you don't mind and see if that works out.

**Comment by troch** [comment]
Cheers. I got it working with the following obscure syntax:

    $ npm install git+https://git@github.com/aurelia/http-client

Had to do the same with aurelia/path as it is a dependency and I can now access it all in the browser. Will try to use it later.
