### ISSUE TITLE
API suggestion: replace `request` getter with `createRequest` method

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/http-client#27]
I think the `HttpClient.request` getter is an awkward way to create a new request. The getter makes it look like it's mutating the client's state, or something. I think the API would be considerably clearer if it were a method instead.

Current API:
```javascript
client.request
  .withParams({ foo: 'bar' })
  .get(uri);
```

Proposed API:
```javascript
client.createRequest()
  .withParams({ foo: 'bar' })
  .get(uri);
```

**Comment by kristianmandrup** [comment]
createRequest obviously looks like a factory method, like you are building a new request instance which is more clear incase you are always creating a new instance and never reusing one. In that case you might as well aloe the params hash to be passed directly as an argument to the factory method.
