### ISSUE TITLE
Client should set sensible Content-Type header on request by default

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/http-client#39]
Several users have complained that using the client to post JSON content sends a Content-Type of text/plain. We should set the header by default when we serialize JSON.

I can look into this.

**Comment by Zoltu** [comment]
:+1: 	Just ran into this today.

**Comment by bfil** [comment]
Yeah same here, docs say by default the client handles JSON, so adding the header by default could make sense.

**Comment by chovy** [comment]
I don't know, its easy enough to set yourself. I think it's more flexible to not assume anything.

```
    this.http = http.configure(x => {
      x.withHeader('Content-Type', 'application/json');
      //x.withCredentials(true);
    });
```
