### ISSUE TITLE
Feature request:  `params` argument for http-client.get()

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/http-client#4]
Allow a `params` argument to be passed to the `get` method of aurelia-http-client. The get command would build a query string based on the object keys and values.

**Comment by EisenbergEffect** [comment]
Ok. I closed the issue. Let's continue discussion here on api design.

**Comment by jedd-ahyoung** [comment]
So I've stubbed out the request API so far; I haven't tested it, but I think that the shorthand and longhand should work. I've moved the HTTP verb functions out of `http-client` and into an `http-builder` module. The `http-client` module is now a simple wrapper for the builder, exposing the builder's verb functions. I'm trying to figure out the best way to handle function registration, though.

One option is possibly to add a BuilderAction class, with a static `registerAction` function. The HttpBuilder class could keep a reference to a BuilderAction instance and perhaps delegate certain functions to it? This would mean that plugins could call `BuilderAction.registerAction('withParams', myFunction)`.

I'm on the lookout for more options, though, along with implementation details. What does everyone think about this? Any possible pitfalls?

**Comment by EisenbergEffect** [comment]
So, since we are in JavaScript you can do this pretty easily. What you need is a helper function that simply adds new functions onto the prototype of the builder. I used this technique on the metadata api. So, you can see this in that repo.

**Comment by jedd-ahyoung** [comment]
I was originally thinking this wouldn't work because prototype functions can't access instance variables. However, that's only true for private variables declared as a var in the constructor - prototypes can't access variable within a closure, but they can access class members. I'm going to work on this and submit a pull request soon.

**Comment by yelvert** [comment]
@EisenbergEffect I have implemented a params to querystring builder class in a local project that uses an extracted version of jquery $.params method. If you would like, If you think it would be worth a look, I'll add it in to HttpClient and submit a PR

**Comment by yelvert** [comment]
Or I could look at adding it in to #13.

**Comment by jedd-ahyoung** [comment]
@Tayler See an earlier pull request here -
https://github.com/aurelia/http-client/pull/5. I implemented something
similar and there was mention (possibly by me) about adding it as a utility
function in `aurelia-path`. Just a heads up, since the history for this
issue discussion is split across multiple PRs.

**Comment by yelvert** [comment]
Ok, Thanks, I'll take a look at that before I do anything. I was thinking about doing something like
```
http.(get/delete/jsonp)(uri, params)
http.(post/put/patch)(uri, {params, content})
```

**Comment by yelvert** [comment]
I took a stab late last night and came up with https://github.com/aurelia/path/pull/3 and https://github.com/aurelia/http-client/pull/15
