### ISSUE TITLE
IE11 - POST sending "undefined" string in body instead of empty string when no second param is passed to post

### ISSUE THREAD

**Issue by hobbit125** [aurelia/http-client#41]
Configuration
```
        this.http = http.configure(x => {
            x.withHeader('Content-Type', 'application/json');
            x.withCredentials(true);
        });
```

When you call post like this:

```
    this.http.post('http://somehost/someservice');
```

In chrome, it will send an empty body.  This is what would be expected for a JSON post with no request object.

In IE 11, however, it sends a body containing the string "undefined."  This is not expected behavior and tends to fail as the bare string "undefined" is not valid json.

The current workaround, is to explicitly pass the request object as null, which will work in both IE and chrome:

```
    this.http.post('http://somehost/someservice', null);
```

**Comment by chovy** [comment]
I think it actually checks now.

**Comment by EisenbergEffect** [comment]
I think this is fixed.
