### ISSUE TITLE
Can't set X-ZUMO-APPLICATION in request header

### ISSUE THREAD

**Issue by johnmurphy01** [aurelia/http-client#49]
I am creating an Aurelia web project that will consume an API. The API is housed as an Azure Mobile Service. I know I need to add the X-ZUMO Auth header to the request. But, when I instantiate my http client, that header never makes it to the request headers according to the browser dev tools.When I run this in my application, I am presented with a login screen I presume because the X-ZUMO header is not present so the app doesn't have permissions to run. I am running this using gulp which is setting up a local instance of the web application for me. I also tried the external IP address.

I'd love to use Aurelia for this new project, but if I can't get past this point I'll need to go to something else.

Here is my web api class:
``` javascript
import {HttpClient} from 'aurelia-http-client';

export class WebApi
{
static inject = [HttpClient];
constructor(http)
{
    this.http = http;
    this.baseUrl = 'https://myProject.azure-mobile.net/';
    this.zumoHeader = 'X-ZUMO-APPLICATION';
    this.zumoKey = 'zumoKey';
    this.client = new HttpClient()
        .configure(x => {
        x.withBaseUrl(this.baseUrl);
        x.withHeader(this.zumoHeader, this.zumoKey);
    });
}

// requests will go here
testGet()
{
    this.client.jsonp('api/logs?application_id=sessionID&__count=20')
    .then(response =>
    {
        alert(response);
    });
}
} 
```

**Comment by EisenbergEffect** [comment]
@johnmurphy01 Please don't discard Aurelia on account of an http issue. Bear in mind that our HttpClient is an optional module, but it is by no means necessary. You can use whatever library you want to access your web services.

That said, we would like to see if we can help you resolve this issue. 

Currently, you can't send headers with our jsonp api. Actually, I don't think you can do that at all from the browser. I'm not 100% sure....but I'm pretty close to 100%. @bryanrsmith Have you ever encountered this?

@johnmurphy01 Are you sure you don't want to use a simple `get` method instead? This would make a huge difference.

**Comment by johnmurphy01** [comment]
@EisenbergEffect I was just about to post that I was able to get further using a `get` request instead. I still have issues but I think it's now a CORS problem and it's up to myself and my server architect to resolve. I figured I could still use Aurelia with a separate http library. Thanks for your help and support!

**Comment by EisenbergEffect** [comment]
Great news. That makes sense. You will need to set up some CORS permissions on the server, but then you should be good to go. I'm going to close this issue. If anything else crops up, create a new issue for that and we'll work to resolve it.

**Comment by bryanrsmith** [comment]
CORS is definitely the way to go. Jsonp can't support setting headers, or really any customization. 

If you do find shortcomings in Aurelia's http client that other libraries handle better, do let us know & we'll be happy to check it out!
