### ISSUE TITLE
No header returned in response

### ISSUE THREAD

**Issue by cybertony** [aurelia/http-client#51]
I think returned headers are missing in response. 
Below the code example and screenshots
``` 
return this.http.post(this.url, this.credentials).then(response => {
    	console.log(response.getAllResponseHeaders());
});              
```
![2](https://cloud.githubusercontent.com/assets/5312754/7857532/5278b80a-0531-11e5-9065-f1b9b58ec71b.png)

![1](https://cloud.githubusercontent.com/assets/5312754/7857534/552a6986-0531-11e5-8254-87863443354b.png)

**Comment by EisenbergEffect** [comment]
@bryanrsmith When you get a chance, can you investigate?

**Comment by heruan** [comment]
It may be CORS related: the browser will inject response header into the XHR object only if they are listed in the response `Access-Control-Expose-Headers` header which is not set in the debugged response.
