### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dpinart** [aurelia/http-client#52]
Hi,

Using xmlhttprequest I can send user credential (username and password) using open method overload " open(method, url [, async = true [, username = null [, password = null]]])"
how can I send user credentials  with aurelia-http-client?

thanks in advance

**Comment by EisenbergEffect** [comment]
@bryanrsmith When you get a chance to check this out... I can't remember if this was covered already. If not, we can handle this with a transformer probably.
