### ISSUE TITLE
jspm package does not contain the interceptor functionality.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/http-client#55]
My apologies upfront for not being hindered too much by in depth jspm knowledge, but the jspm package for http-client 0.8.1 doesn't seem to contain the interceptor functionality in github for the same version.
What is precisely workflow here ?
In github I would expect that in the dist/system folder, the up to date compiled stuff would be present ? There is still an old 'build'. I guess jspm is taken its sources from there.

**Comment by EisenbergEffect** [comment]
The version with interceptors hasn't been released yet. That is in master and will release in the next couple of days.
