### ISSUE TITLE
Track outstanding http calls

### ISSUE THREAD

**Issue by zewa666** [aurelia/http-client#6]
It would be nice if we had a way in the client to know if there are some outstanding request. This could be quite helpful in combination with E2E tests (as mentioned here https://github.com/aurelia/framework/issues/12) so we start testing only when the initial work is really done, including any http calls during initial page creation

**Comment by meenie** [comment]
I believe that's what Protractor does in AngularJS.  It's tied in to know when everything is booted up and also keeps track of the HTTP calls.

**Comment by zewa666** [comment]
Nope thats part of the $httpBackend Module
https://docs.angularjs.org/api/ngMock/service/$httpBackend#verifyNoOutstandingRequest

Protractor just uses the api but doesnt provide it.

**Comment by meenie** [comment]
Ya, sorry, that's what I meant.  It uses `$httpBackend` api.  I was supporting what you were requesting because it's the type of thing used by tools like Protractor.

**Comment by EisenbergEffect** [comment]
@zewa666 Is the idea here that any time we make a request, we push track that and then any time it resolves we remove it from our list. Any time there's nothing left in the list, we raise some event?

**Comment by zewa666** [comment]
Sry have been quite busy the last days ... essentially yes @EisenbergEffect. We just need to maintain a queue of all active requests. On empty list just raise event or allow manual polling, or better both :). Dunno if promises suite for that but what would you think of something like this:

```js
let emptyQueueNotification = HttpClient.notifyOnEmptyQueue()
  .then( (msg) => { // Do my work here });
```

**Comment by EisenbergEffect** [comment]
@zewa666 Take a look at the http-client master branch. There's a placeholder in there to raise an event. Let me know if this is correct. Also, we need to figure out how to handle the event subscription. Let me know if you have any ideas on that.

**Comment by zewa666** [comment]
Spot looks good, as far as I understand the code if multiple requests are queued the event will only be raised after last one is done or failed right?
Regarding event subscription I'm not sure what you mean. Is it a question whether to raise a Custom-Event like for Aurelia Composed or to leverage Pub-Sub like EventAggregator?
I'd be fully ok with doing it the way like the Aurelia Composed event, but I guess I just missed the point here :)

**Comment by EisenbergEffect** [comment]
The upcoming release (currently in master) tracks pending requests. When all are complete it will call `client.onRequestsComplete`. To hook into this, simply install your own function there.
