### ISSUE TITLE
Adding a header inside an interceptor seems not to work.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/http-client#60]
By design?

export class AuthenticateInterceptor {
  request(message) {
        message.headers.add("Authorization", "bearer 123");
    return message;
}
   }

**Comment by Mordred** [comment]
That's because all transformers are run before interceptors. `headerTransformer` is copying headers to the XHR, so modifying `message.headers` inside interceptor will not copy new values to the XHR. 

Maybe we can remove `headerTransformer` and configure XHR headers inside `processRequest`: https://github.com/aurelia/http-client/blob/master/src/request-message-processor.js#L82

@EisenbergEffect What do you think?

This problem can also be with other transformers which modifies XHR directly.

**Comment by paulvanbladel** [comment]
Thanks for helping.
I can't judge whether or not that would be a good design decision, but adding a json token via an interceptor feels like the correct place to do this, otherwise it need to be added in every HttpClient request created.
Please advice if you would do it differently.

**Comment by alexanderchr** [comment]
What stops all the XHR transformers from being run in `processRequest`? As i understand it nothing happens between request interceptors and processRequest and the request intereceptors are not dependant on the xhr transformers being run first.

**Comment by Mordred** [comment]
Adding interceptor is done by transformer. So you have to run all transformers to build the message, than you can schedule interceptors. Running transformers inside `processRequest` is too late. But maybe I'm wrong - if you have some idea, make a PR.

**Comment by alexanderchr** [comment]
Isn't there two kinds of transformers? The transformers adding the interceptors are run in HttpClient (https://github.com/aurelia/http-client/blob/master/src/http-client.js#L94) while the ones running in RequestMessageProcessor seems to be the ones responsible for modifying the XHR. As they barely touch the message it should be possible to delay those a bit. I'll look close at it.

**Comment by atsu85** [comment]
@paulvanbladel 
I also stumbled upon this issue.

> otherwise it need to be added in every HttpClient request created.

I hope you didn't start adding the header manually everywhere. My solution was to add a transformer instead of interceptor:
```TypeScript
    http.configure((reqBuilder: RequestBuilder) => {
      // reqBuilder.withInterceptor(new CustomHttpInterceptor()); // doesn't work because of this issue
      reqBuilder.transformers.push((client, processor, message: HttpRequestMessage, xhr) => {
          message.headers.add('some-header', getHeaderValue());
      });
    });
```

**Comment by paulvanbladel** [comment]
Thank will try that.
