### ISSUE TITLE
Treating JSON response as text (for IE).

### ISSUE THREAD

**Issue by salminio** [aurelia/http-client#66]
I was wondering if rather than forcing all JSON typed responses to be of type text that then requires the end user to parse into json - would it be better to have a post processor for just IE and let the browser native parsing of the response work as intended. This should improve performance in chrome and firefox and all browsers who natively support json as a response type. I believe this is how jquery does it (not 100% sure).

export function responseTypeTransformer(client, processor, message, xhr){
  var responseType = message.responseType;

  if(responseType === 'json'){
    responseType = 'text'; //IE does not support json
  }

  xhr.responseType = responseType;
}

**Comment by EisenbergEffect** [comment]
We would certainly consider that. Would you consider putting together a PR to do that?

**Comment by EisenbergEffect** [comment]
Closing for now since no response or PR from the original submitter and no upvotes from the community.
