### ISSUE TITLE
Add Accept header by default set to application/json

### ISSUE THREAD

**Issue by bychkov** [aurelia/http-client#69]
We had an issue when Firefox was sending http request it sets the following Accept header:
`text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
And that makes WebAPI to default to XML formatter for response. 

Chrome and IE just send `*/*` and json is rendered by default.

Setting Accept to 'application/json' should provide uniformity between the browsers.

**Comment by bryanrsmith** [comment]
I think that would result in confusing behavior for anyone making requests for non-JSON content.

If you don't want WebAPI to use the XML formatter, you should remove that formatter. Alternatively, you can configure the HttpClient to always add the Accept header. I don't think we want to do that be default, though.
