### ISSUE TITLE
Intercept calls for Testing

### ISSUE THREAD

**Issue by zewa666** [aurelia/http-client#7]
Angular provides a quite nice service called [ngMockE2E](https://docs.angularjs.org/api/ngMockE2E/service/$httpBackend) which enables intercepting any outgoing http calls and responding with mocks.

Not only is this useful for mocking real requests for testing, but would also allow to do [Backend-less Development](http://cloudspace.com/blog/2014/03/27/backend-less-development-with-angular/#.VMpGZ2iG9VY) which is a really nice thing if your Backend and Frontend team wants to adhere to agreed interfaces.

**Comment by AshleyGrant** [comment]
Isn't that just a complicated way of monkey patching the angular `$http`?

This code from the angular site that demos the service seems like it could just be replaced with an ES6 class to wrap that api:

```javascript
myAppDev = angular.module('myAppDev', ['myApp', 'ngMockE2E']);
myAppDev.run(function($httpBackend) {
  phones = [{name: 'phone1'}, {name: 'phone2'}];

  // returns the current list of phones
  $httpBackend.whenGET('/phones').respond(phones);

  // adds a new phone to the phones array
  $httpBackend.whenPOST('/phones').respond(function(method, url, data) {
    var phone = angular.fromJson(data);
    phones.push(phone);
    return [200, phone, {}];
  });
  $httpBackend.whenGET(/^\/templates\//).passThrough();
  //...
});
```

Seems to me that just writing an ES6 class to wrap around calls to that API and handle the faking of data during development. Using the flickr example in skeleton navigation:

Here's a gist to show what I'm talking about: https://gist.github.com/AshleyGrant/55b3763c5a9bf7fe2577

Obviously, there would need to be a gulp task or some such to swap between the real and mock apis as just commenting/uncommenting is not a real solution.

**Comment by EisenbergEffect** [comment]
No task needed to swap them out actually. We can use DI to provide an alternate class to use that maps to HttpClient.

**Comment by AshleyGrant** [comment]
Or maps to the wrapper class the developer writes to wrap around api calls. FlickrApi in this case. Could you modify the gist to show how to do that?

**Comment by zewa666** [comment]
Ok that would work the way but still require the developer to manually go through each service and mock it. ngMockE2E on the other hand really immediatelly catches all requests and intercepts them. Then in one place you can easily setup the responses but per route pattern.

Again it is the same thing but it is much nicer to write since you place everything in one config and additionally do not need to touch the production files. It gets very interesting when you test multiple scenarios. E.g. for a client of mine we mock that way different testcases, one with large chunk of data, a medium sized and something only for developers to be able to quickly build and test the app. Then using grunt I just need to switch out the config and not modify X files to require the mock.

In Durandal I did something similar with the requirejs.map feature, where I'd simply replace the requirejs config which then points to the mocks instead of the concrete implementation.

Hope I have been able to give you a better picture of what I try to achieve.

**Comment by AshleyGrant** [comment]
For testing, jasmine already has mocking of http stuff built in, so no need for us to reinvent the wheel for that. On the dev side, I don't think my is that far out of line for a larger application where talking to the API would be abstracted away to a service class like I wrote anyways. In that case, I think an argument could made that the solution I gave above of creating a mock class is worth consideration since the service class would be injected in to your code that needs to talk to the api and not http-client (flickr.js in this case gets flickr-api.js injected and not http-client).

Thoughts?

**Comment by zewa666** [comment]
When we talk about testing don't forget about E2E Tests. There is nothing that drives me more crazy then external http requests for Facebook or whatever foo that just consume valuable time for Protractor to run the test-suite. Same behaves with Testing lists. I don't need 50 records, 10 are most of the time enough to guarantee the functionality.
So for those kind of tests its pretty nice being able to switch out the real implementation quickly.

Again all of this is around keeping the mocks at one place instead of distributed across several files. Besides that this way no need to create a lot of overhead (class, functions etc.) you just define the response for specific routes and thats it. When consulting dev-teams with nasty managers its all about performance, for both sides, so the easier testing gets, the more it will be used.
The Mock-Everything-By-Default bandwagon seems also getting larger with stuff like FBs Jest.

**Comment by EisenbergEffect** [comment]
We could "teach" the DI Container to automatically mock anything that isn't  explicitly registered. So, add an api that you can use to pass it a "create mock" function. Any thoughts on that?

**Comment by zewa666** [comment]
Just for the sake of completeness I've created a branch to show what I was thinking about (https://github.com/zewa666/http-client/tree/demo-mockedRequests). Currently it has just mocked the GET request. Don't look at the code its messy and completely unclean, but take a look at the [unit-test](https://github.com/zewa666/http-client/blob/demo-mockedRequests/test/http-mocks.spec.js) to see what I meant.

**Comment by EisenbergEffect** [comment]
New client has the concepts of RequestProcessors. A mocking processor could be dropped in for this purpose. New version releasing in the next couple of days. Code is in master now.

**Comment by mjwwit** [comment]
@EisenbergEffect I can see various references to `RequestMessageProcessor`s in the code but I fail to see how the concept can be leveraged to provide response mocking functionality.

I tried using a request `Interceptor` in the hopes of short-circuiting by returning a `HttpResponseMessage`, but this results in the `HttpClient` continuing with the request and returning its response instead of the short-circuited `HttpResponseMessage`.

I see how the `RequestMessageProcessor` concept is used to prepare the XHR request, but I don't see a way to provide a custom one. Can you explain (in a bit more detail) how this can be achieved?
