### ISSUE TITLE
http-client 0.10.2 missing index.js file: causing undefined error on import

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/http-client#76]
When I try to import the http-client in code, with version 0.10.2, I get an error saying that the HttpClient is undefined. I believe this is because the index.js file is missing from the src directory. Can someone help to confirm this? I want to see if others are running into the same issue before I issue a pull request for this.

**Comment by EisenbergEffect** [comment]
Try updating to the latest. We did releases last night and we know we had an issue with http client, so we fixed it then. The community member was then able to use it successfully.

**Comment by jedd-ahyoung** [comment]
Still having trouble. I did the following:

Jedds-MBP:kali-web jahyoung$ jspm uninstall aurelia-http-client
         Clearing configuration for github:aurelia/http-client@0.10.2
         Clearing configuration for github:aurelia/http-client@0.9.1
         Removing package files for github:aurelia/http-client@0.10.2
         Removing package files for github:aurelia/http-client@0.9.1
         Removing package files for github:aurelia/path@0.7.0

    ok   Uninstall complete.
     

    Jedds-MBP:kali-web jahyoung$ 
    Jedds-MBP:kali-web jahyoung$ jspm install aurelia-http-client
         Updating registry cache...
         Looking up github:aurelia/http-client
         Looking up npm:core-js
         Looking up github:aurelia/path

    warn core-js is installed in the config file, but is not a dependency in the package.json. It is advisable to add it to the package.json file.
         Looking up github:systemjs/plugin-json
         Looking up github:jspm/nodelibs-fs
         Looking up github:jspm/nodelibs-process
         Looking up npm:process
    ok   Installed aurelia-http-client as github:aurelia/http-client@^0.10.2 (0.10.2)
         Installed Forks

                            github:aurelia/path 0.6.1 0.8.1
                  github:pwkad/aurelia-bs-modal master 0.2.1
                                 npm:babel-core 5.2.2 5.8.14
                                      npm:bn.js 2.2.0 3.1.1
                                    npm:process 0.10.1 0.11.1
         
         To inspect individual package constraints, use jspm inspect endpoint:name.


    ok   Install complete.

And I'm getting the following error:

    Error: Error instantiating AuthenticationService.
    ------------------------------------------------
    inner error: Error: key cannot be null or undefined.
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:117:19)
        at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
        at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:135:32)
        at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
        at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:131:28)
        at http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/composition-engine.js:108:79
        at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    ------------------------------------------------
    inner error: Error: key cannot be null or undefined.
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:117:19)
        at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
        at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:135:32)
        at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
        at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:131:28)
        at http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/composition-engine.js:108:79
        at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
        at AggregateError (http://localhost:9000/jspm_packages/github/aurelia/logging@0.4.0/index.js:24:15)
        at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:200:19)
        at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:141:26)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:135:32)
        at Container.invoke (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:195:30)
        at Array.<anonymous> (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:78:48)
        at Container.get (http://localhost:9000/jspm_packages/github/aurelia/dependency-injection@0.7.1/container.js:131:28)
        at http://localhost:9000/jspm_packages/github/aurelia/templating@0.11.2/composition-engine.js:108:79
        at run (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)

When I console.log HttpClient (the import), I get "undefined". If I roll back to 0.9.1 I don't run into this error.

**Comment by EisenbergEffect** [comment]
Try updating all your aurelia deps with an install command. You've got old versions of things lying around. I can see it in the error log. There may be something going wrong there.

**Comment by jedd-ahyoung** [comment]
Tried an install and then an update. From what I'm reading, JSPM update may only update within the semver range, which may be my problem; I started this project using a copy of the contacts-app.
    Installed Versions
    
                         github:aurelia/binding 0.6.1
                    github:aurelia/bootstrapper 0.12.0
            github:aurelia/dependency-injection 0.7.1
                github:aurelia/event-aggregator 0.4.0
                       github:aurelia/framework 0.11.0
                         github:aurelia/history 0.4.0
                 github:aurelia/history-browser 0.4.0
           github:aurelia/html-template-element 0.2.0
                     github:aurelia/http-client 0.10.2
                          github:aurelia/loader 0.6.0
                  github:aurelia/loader-default 0.7.0
                         github:aurelia/logging 0.4.0
                 github:aurelia/logging-console 0.4.0
                        github:aurelia/metadata 0.5.0
                            github:aurelia/path 0.6.1 0.8.1
                github:aurelia/route-recognizer 0.4.0
                          github:aurelia/router 0.8.1
                      github:aurelia/task-queue 0.4.0
                      github:aurelia/templating 0.11.2
              github:aurelia/templating-binding 0.11.0
            github:aurelia/templating-resources 0.11.1
               github:aurelia/templating-router 0.12.0
                       github:components/jquery 2.1.4
                    github:jspm/nodelibs-assert 0.1.0
                    github:jspm/nodelibs-buffer 0.1.0
             github:jspm/nodelibs-child_process 0.1.0
                 github:jspm/nodelibs-constants 0.1.0
                    github:jspm/nodelibs-crypto 0.1.0
                    github:jspm/nodelibs-events 0.1.1
                        github:jspm/nodelibs-fs 0.1.2
                      github:jspm/nodelibs-http 1.7.1
                    github:jspm/nodelibs-module 0.1.0
                       github:jspm/nodelibs-net 0.1.2
                      github:jspm/nodelibs-path 0.1.0
                   github:jspm/nodelibs-process 0.1.1
                    github:jspm/nodelibs-stream 0.1.0
            github:jspm/nodelibs-string_decoder 0.1.0
                    github:jspm/nodelibs-timers 0.1.0
                       github:jspm/nodelibs-tty 0.1.0
                       github:jspm/nodelibs-url 0.1.0
                      github:jspm/nodelibs-util 0.1.0
                        github:jspm/nodelibs-vm 0.1.0
                  github:pwkad/aurelia-bs-modal master 0.2.1
                      github:rstacruz/nprogress 0.1.6
                     github:systemjs/plugin-css 0.1.13
                    github:systemjs/plugin-json 0.1.0
                          github:twbs/bootstrap 3.3.5
           github:webcomponents/webcomponentsjs 0.6.3
                                     npm:Base64 0.2.1
                                    npm:asn1.js 2.1.3
                                     npm:assert 1.3.0
                                 npm:babel-core 5.2.2 5.8.19
                              npm:babel-runtime 5.2.2
                                  npm:base64-js 0.0.8
                                      npm:bn.js 2.2.0 3.1.1
                                    npm:brorand 1.0.5
                             npm:browserify-aes 1.0.2
                             npm:browserify-rsa 2.0.1
                            npm:browserify-sign 3.0.2
                                     npm:buffer 3.3.1
                                 npm:buffer-xor 1.0.2
                       npm:constants-browserify 0.0.1
                                    npm:core-js 0.9.18
                               npm:core-util-is 1.0.1
                                npm:create-ecdh 2.0.1
                                npm:create-hash 1.1.1
                                npm:create-hmac 1.1.3
                          npm:crypto-browserify 3.9.14
                             npm:diffie-hellman 3.0.2
                                   npm:elliptic 3.1.0
                                     npm:events 1.0.2
                               npm:font-awesome 4.4.0
                                    npm:hash.js 1.0.3
                                    npm:ieee754 1.1.6
                                    npm:indexof 0.0.1
                                   npm:inherits 2.0.1
                                   npm:is-array 1.0.1
                                    npm:isarray 0.0.1
                               npm:miller-rabin 2.1.0
                        npm:minimalistic-assert 1.0.0
                                 npm:parse-asn1 3.0.1
                            npm:path-browserify 0.0.0
                                     npm:pbkdf2 3.0.4
                                    npm:process 0.10.1 0.11.1
                             npm:public-encrypt 2.0.1
                                   npm:punycode 1.3.2
                                npm:querystring 0.2.0
                                npm:randombytes 2.0.1
                            npm:readable-stream 1.1.13
                                  npm:ripemd160 1.0.1
                                     npm:sha.js 2.4.2
                          npm:stream-browserify 1.0.0
                             npm:string_decoder 0.10.31
                          npm:timers-browserify 1.4.1
                             npm:tty-browserify 0.0.0
                                        npm:url 0.10.3
                                       npm:util 0.10.3
                              npm:vm-browserify 0.0.4
         
         To inspect individual package constraints, use jspm inspect endpoint:name.

**Comment by EisenbergEffect** [comment]
Yes, because in a pre 1.0 version, changes to the minor version are considered breaking changes, therefor jspm will not update those unless you specifically re-install them. This will get much simpler after we go 1.0 where the changes for a long period of time will be just minor and path -  non breaking.

Yep, your Aurelia stuff is way out of date. Here's a quick script that should update all of it:

```
jspm install aurelia-animator-css aurelia-binding aurelia-bootstrapper aurelia-dependency-injection aurelia-framework aurelia-http-client aurelia-router aurelia-event-aggregator aurelia-history-browser aurelia-loader-default aurelia-loader aurelia-metadata aurelia-route-recognizer aurelia-templating-binding aurelia-templating-resources aurelia-templating-router aurelia-templating aurelia-logging aurelia-task-queue aurelia-history aurelia-path  
```
