### ISSUE TITLE
Better HTTP header support

### ISSUE THREAD

**Issue by heruan** [aurelia/http-client#77]
The plugin manages the HTTP header as it was just a plain `{ key: value }` object, where HTTP RFC2616 states that header fields can appear multiple times, e.g. this could be a valid response:

```
HTTP/1.1 200 OK
...
X-Modified-By: <heruan>; timestamp="1436536800"
X-Modified-By: <holly>; timestamp="1438359715"
```

and also have a well-defined syntax: `field-name: field-value[; param1="value", param2="value"]`, for example the `Link` header (e.g. used to link a JSON schema URI to a response) may appear as:
`Link: <http://example.org/api/users/$schema>; rel="describedBy"`. Also field names should be treated case-insensitive.

Why not use a `Map` or a `Set` to store header fields in the `Headers` class, with methods to query and retrieve the field value separately from parameters? It would really improve the plugin.
—
See:
- https://www.ietf.org/rfc/rfc2616.txt
- https://tools.ietf.org/rfc/rfc5988.txt
- http://json-schema.org/latest/json-schema-core.html#anchor35

**Comment by alexanderchr** [comment]
Great suggestion. Treating headers according to the spec is essential, and having parameters handled would be nice.

Right now headers are added by running a transformer on the request message. This mean it's impossible to remove or modify a header that has been once configured, except by calling `withHeader` again. We can therefore not modify `withHeader` to add the same header more than once when called multiple times. The solution would be to allow `withHeader` to be called with an array: `withHeader('name', ['instance1ofheader', 'instance2ofheader'])`. I believe this is kind of hacky, and that we should revamp the transformer system(#68), but this would be a quick fix in the meantime.

We'll also have to take a look at header parsing, it looks like it will break down if the same header is present more than once. The rest is pretty trivial and should be doable without too many breaking changes.

**Comment by EisenbergEffect** [comment]
Please send PRs. I am sure we can work out the solution.

**Comment by EisenbergEffect** [comment]
@bryanrsmith See above. Need to think about this for http client and possible also for fetch.

**Comment by bryanrsmith** [comment]
aurelia/fetch-client uses the Fetch API's [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) and [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) types. It should be pretty simple to rework aurelia/http-client's Headers class to work more like the built-in one, so you can add multiple header values under the same name. We could borrow the Headers implementation from [Github's Fetch polyfill](https://github.com/github/fetch/blob/master/fetch.js) if we want it to work the same.

**Comment by EisenbergEffect** [comment]
@bryanrsmith I would support that change. If you borrom that implementation, please add an acknowledgements markdown file to this repo and indicate thier license as well as a short thank you message to them for their work.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Did you want to get this in for the beta? or do you think we can do it as a non-breaking change for beta 2?

**Comment by Alexander-Taran** [comment]
Stale since 2015

**Comment by Alexander-Taran** [comment]
@EisenbergEffect added to vNext candidates list.
Can be closed
