### ISSUE TITLE
Something like $.ajaxPrefilter()

### ISSUE THREAD

**Issue by Zensavona** [aurelia/http-client#89]
Hi guys, this is more a feature request than an issue. 

I'd love a way of being able to sanely filter request responses in a similar way to `jQuery.ajaxPrefilter()`. The use case is looking for things like 401s and determining login state on each request - is there currently a hook for doing this I'm unaware of? The only way I'm aware of is wrapping the request methods in some way, which seems a bit ugly.

Thoughts?

Thanks :heart:

**Comment by bryanrsmith** [comment]
You should be able to accomplish this with an interceptor. Check out the documentation at http://aurelia.io/docs.html#interceptors and let us know if that doesn't meet your needs.

**Comment by Zensavona** [comment]
Perfect. Thanks @bryanrsmith!
